### PR TITLE
Fix restore allocation when transitioning from an SP to a broadcast CBAP and vice versa

### LINKED ISSUE #6: STA with allocated SP can participate in a CBAP
A STA or AP with an allocated SP can participate in a subsequent CBAP, if present. We may want to prevent a STA or AP with an allocated SP from participating in a contention-based access period.

### LINKED ISSUE #11: MacLow ResumeTransmission method issue
When the method ResumeTransmission at MacLow is called in order to complete a previously suspended transmission, the suspended allocation (packet/header ..) is restored and a check is performed given the full transaction duration (i.e. transmission of the data packet + possible acks) adn the remaining allocation time. If the latter is greater then the former, the packet is transmitted; however, the opposite case is not handled. Should the packet be store again for future transmission?
If this case is not handled, the aggregateQueue parameter, filled with packets belonging to the restored allocation, is not flushed; therefore, the subsequent transmission of new packets by the MacLow throws an out-of-range error because the aggregate is referring to a different packet allocation.

### PR DESCRIPTION
**Pull request by tommyazz**
Now a STA can communicate smoothly between SPs and broadcast CBAPs with the AP and vice versa. Still, the communication between two STAs with allocated SP needs to be investigated during a broadcast CBAP.

Fixed #11 
Fixed #6

### CODE REVIEW

File: src/wifi/model/dca-txop.cc [hunk 1]
```diff
@@ -459,7 +485,7 @@ DcaTxop::NotifyAccessGranted (void)
       m_fragmentNumber = 0;
       NS_LOG_DEBUG ("dequeued size=" << m_currentPacket->GetSize () <<
                     ", to=" << m_currentHdr.GetAddr1 () <<
-                    ", seq=" << m_currentHdr.GetSequenceControl ());
+                    ", seq=" << std::hex << m_currentHdr.GetSequenceControl () << std::dec);
```
Comment (mattia-lecci) [inline src/wifi/model/dca-txop.cc]: 0x

File: src/wifi/model/dca-txop.h [hunk 2]
```diff
@@ -330,6 +330,10 @@ class DcaTxop : public Object
    * End Current Contention Period.
    */
   void EndAllocationPeriod (void);
+  /**
+   * Restore Allocation.
+   */
+  void RestoreAllocation (void);
```
Comment (mattia-lecci) [inline src/wifi/model/dca-txop.h]: Need more detailed documentation

File: src/wifi/model/dca-txop.cc [hunk 3]
```diff
@@ -274,6 +274,46 @@ DcaTxop::StartAccessIfNeeded (void)
     }
 }
 
+void
+DcaTxop::RestoreAllocation (void)
```
Comment (mattia-lecci) [inline src/wifi/model/dca-txop.cc:278]: Need to discuss for possible collisions

File: src/wifi/model/mac-low.h [hunk 4]
```diff
@@ -382,21 +382,21 @@ class MacLow : public Object
...
-  void RemoveCurrrentAllocation (void);
+  void RemoveCurrentAllocation (void);
   /**
    * Resume Transmission for the current allocation if transmission has been suspended.
    * \param listener
    */
   void ResumeTransmission (Time duration, Ptr<DcaTxop> dca);
 
-  void ChangeAllocationPacketsAddress (AllocationID allocationId, Mac48Address destAdd);
+  void ChangeAllocationPacketsAddress (Mac48Address currentSrc, Mac48Address currentDst, Mac48Address destAdd);
```
Comment (mattia-lecci) [inline src/wifi/model/mac-low.h:401]: Add doc

File: src/wifi/model/mac-low.h [hunk 5]
```diff
@@ -382,21 +382,21 @@ class MacLow : public Object
...
   /**
    * Restore Allocation Parameters for specific allocation SP or CBAP.
    * \param allocationId The ID of the allocation.
    */
-  void RestoreAllocationParameters (AllocationID allocationId);
+  void RestoreAllocationParameters (AllocationID allocationId, Mac48Address srcAddress, Mac48Address dstAddress);
```
Comment (mattia-lecci) [inline src/wifi/model/mac-low.h]: update doc

File: src/wifi/model/mac-low.h [hunk 6]
```diff
@@ -1147,11 +1147,14 @@ double mpduSnr;
     Ptr<WifiMacQueue> aggregateQueue;
   } AllocationParameters;
 
-  typedef std::map<AllocationID, AllocationParameters> AllocationPeriodsTable;
+  typedef std::pair<Mac48Address, Mac48Address> AddressPair;
+  typedef std::map<AddressPair, AllocationParameters> AllocationPeriodsTable;
   typedef AllocationPeriodsTable::const_iterator AllocationPeriodsTableCI;
   typedef AllocationPeriodsTable::iterator AllocationPeriodsTableI;
   AllocationPeriodsTable m_allocationPeriodsTable;
```
Comment (mattia-lecci) [inline src/wifi/model/mac-low.h]: it would be nice to add some documentation on this variable as it seems quite important and not straightforward to understand without looking at a bunch of code first

File: src/wifi/model/mac-low.cc [hunk 7]
```diff
@@ -571,49 +578,76 @@ MacLow::ResumeTransmission (Time duration, Ptr<DcaTxop> dca)
     }
   else
     {
+      NS_LOG_DEBUG ("No enough time to complete this DMG transaction for Packet=" << m_currentPacket);
```
Comment (mattia-lecci) [inline src/wifi/model/mac-low.cc]: *There is not...

File: src/wifi/model/mac-low.cc [hunk 8]
```diff
@@ -571,49 +578,76 @@ MacLow::ResumeTransmission (Time duration, Ptr<DcaTxop> dca)
...
+      StoreAllocationParameters ();
       m_transmissionSuspended = true;
     }
-
-  /* Remove Allocation from allocation list as we restored it */
-  m_allocationPeriodsTable.erase (m_currentAllocationID);
```
Comment (mattia-lecci) [inline src/wifi/model/mac-low.cc:578]: why was this moved above?

File: src/wifi/model/mac-low.h [hunk 9]
```diff
@@ -1147,11 +1147,14 @@ double mpduSnr;
     Ptr<WifiMacQueue> aggregateQueue;
   } AllocationParameters;
 
-  typedef std::map<AllocationID, AllocationParameters> AllocationPeriodsTable;
+  typedef std::pair<Mac48Address, Mac48Address> AddressPair;
+  typedef std::map<AddressPair, AllocationParameters> AllocationPeriodsTable;
```
Comment (mattia-lecci) [inline src/wifi/model/mac-low.h:1168]: are the dst and src addesses enough? why isn't allocation ID included as well?

File: src/wifi/model/mac-low.cc [hunk 10]
```diff
@@ -571,49 +578,76 @@ MacLow::ResumeTransmission (Time duration, Ptr<DcaTxop> dca)
...
+  if (m_currentAllocationID == BROADCAST_CBAP)
     {
-      NS_LOG_DEBUG ("Restored allocation parameters for AllocationID=" << uint16_t (allocationId));
-      m_currentAllocation = it->second;
+      /* Broadcast CBAP: Restore parameters and packets from the first available allocation */
+      m_currentAllocation = iter->second;
+      NS_LOG_DEBUG ("Restored allocation parameters with srcAddress=" << m_currentAllocation.hdr.GetAddr2 ()
+                    << ", dstAddress=" << m_currentAllocation.hdr.GetAddr1 ()
+                    << ", seq=0x" << std::hex <<  m_currentAllocation.hdr.GetSequenceControl () << std::dec);
+      NS_ASSERT_MSG (m_currentSrcAddress == m_currentAllocation.hdr.GetAddr2 (), "Current Src address should equal Hdr Src address");
```
Comment (mattia-lecci) [inline src/wifi/model/mac-low.cc:630]: why assert instead of setting the src address?

File: src/wifi/model/dmg-sta-wifi-mac.cc [hunk 11]
```diff
@@ -1472,7 +1472,7 @@ DmgStaWifiMac::EndRelayPeriods (REDS_PAIR &pair)
           if (m_aid == m_relayLinkInfo.srcRedsAid)
             {
               /* Switching back to the direct link so change addresses of all the packets stored in MacLow and EdcaTxopN */
-              m_low->ChangeAllocationPacketsAddress (m_currentAllocationID, m_relayLinkInfo.dstRedsAddress);
+              m_low->ChangeAllocationPacketsAddress (m_relayLinkInfo.srcRedsAddress, m_relayLinkInfo.selectedRelayAddress, m_relayLinkInfo.dstRedsAddress);
```
Comment (mattia-lecci) [inline src/wifi/model/dmg-sta-wifi-mac.cc]: too long, break line

File: src/wifi/model/dmg-wifi-mac.cc [hunk 12]
```diff
@@ -329,7 +329,7 @@ DmgWifiMac::StartContentionPeriod (AllocationID allocationID, Time contentionDur
   /* Allow Contention Access */
   m_dcfManager->AllowChannelAccess ();
   /* Restore previously suspended transmission in LowMac */
```
Comment (mattia-lecci) [inline src/wifi/model/dmg-wifi-mac.cc]: *MacLow

File: src/wifi/model/edca-txop-n.cc [hunk 13]
```diff
@@ -302,7 +309,7 @@ EdcaTxopN::NotifyAccessGranted (void)
           m_fragmentNumber = 0;
           NS_LOG_DEBUG ("dequeued size=" << m_currentPacket->GetSize () <<
                         ", to=" << m_currentHdr.GetAddr1 () <<
-                        ", seq=" << m_currentHdr.GetSequenceControl ());
+                        ", seq=" << std::hex << m_currentHdr.GetSequenceControl () << std::dec);
```
Comment (mattia-lecci) [inline src/wifi/model/edca-txop-n.cc]: 0x

File: src/wifi/model/edca-txop-n.cc [hunk 14]
```diff
@@ -1034,23 +1041,20 @@ EdcaTxopN::StartAllocationPeriod (AllocationType allocationType, AllocationID al
...
-          PacketInformation info = it->second;
-          m_currentPacket = info.first;
-          m_currentHdr = info.second;
-          NS_LOG_DEBUG ("Restored packet with seq=0x" << std::hex << m_currentHdr.GetSequenceControl ());
-        }
+      RestoreAllocation ();
+
+      NS_LOG_DEBUG (m_queue->IsEmpty () << ", " << m_baManager->HasPackets () << ", " <<
+                    m_low->RestoredSuspendedTransmission () << ", " << m_currentPacket << ", " << m_queue->GetNPackets () <<
+                    ", accessRequested=" << m_dcf->IsAccessRequested ());
```
Comment (mattia-lecci) [inline src/wifi/model/edca-txop-n.cc]: improve log readability

**Review by mattia-lecci — COMMENTED** [review]
Good job! Needs some polishing

File: src/wifi/model/dca-txop.cc [hunk 15]
```diff
@@ -305,19 +338,12 @@ DcaTxop::EndAllocationPeriod (void)
   /* Store parameters related to this Allocation period which include MSDU/A-MSDU */
   if (m_currentPacket != 0)
     {
-      NS_LOG_DEBUG ("Store packet with seq=0x" << std::hex << m_currentHdr.GetSequenceControl ()
-                    << " for AllocationID=" << +m_allocationID);
-      m_storedPackets[m_allocationID] = std::make_pair (m_currentPacket, m_currentHdr);
+      NS_LOG_DEBUG ("Store packet with seq=0x" << std::hex << m_currentHdr.GetSequenceControl () << std::dec);
+      NS_ASSERT_MSG (m_low->GetAddress () == m_currentHdr.GetAddr2 (), "Current Src address should equal Hdr Src address");
+      m_storedPackets.insert (std::make_pair (AddressPair (m_currentHdr.GetAddr2 (), m_currentHdr.GetAddr1 ()),
+                                              PacketInformation (m_currentPacket, m_currentHdr)));
```
Comment (MatteoDrago) [inline src/wifi/model/dca-txop.cc]: I think that here the indentation exploded

File: src/wifi/model/dmg-wifi-mac.cc [hunk 16]
```diff
@@ -401,7 +401,7 @@ DmgWifiMac::ScheduleServicePeriod (uint8_t blocks, Time spStart, Time spLength,
 void
 DmgWifiMac::StartServicePeriod (AllocationID allocationID, Time length, uint8_t peerAid, Mac48Address peerAddress, bool isSource)
 {
-  NS_LOG_FUNCTION (this << length << static_cast<uint16_t> (peerAid) << peerAddress << isSource << Simulator::Now ());
+  NS_LOG_FUNCTION (this << length << +peerAid << peerAddress << isSource << Simulator::Now ());
```
Comment (MatteoDrago) [inline src/wifi/model/dmg-wifi-mac.cc:404]: why is there the "+" in front of peerAid? Is that a typo or does it mean something?

**Review by MatteoDrago — COMMENTED** [review]
Here I am judging exclusively the code quality. For a detailed analysis of how this code works, I'd like to do a one-to-one discussion / code walk-through, when possibile.

File: src/wifi/model/dmg-wifi-mac.cc (hunk 16 above)
Comment (mattia-lecci) [reply src/wifi/model/dmg-wifi-mac.cc:404]: peerAid is a uint8_t. By default, operator<< interprets it as a character printing unexpected and meaningless logs. You need to cast it or do something with it in order to properly display it in the logs, and I think adding a plus in front of it does just that.
Check it out [here](https://stackoverflow.com/questions/19562103/uint8-t-cant-be-printed-with-cout).

File: src/wifi/model/mac-low.cc (hunk 10 above)
Comment (tommyazz) [reply src/wifi/model/mac-low.cc:630]: At this stage, m_currentSrcAddress should be equal to the source address of the restored allocation. It's just a sanity check, maybe somehow useless :(

File: src/wifi/model/mac-low.h (hunk 9 above)
Comment (tommyazz) [reply src/wifi/model/mac-low.h:1168]: Allocation ID is not useful. In the case of a broadcast CBAP whose allocation ID is 0, if a suspended transmission is stored with (ID, sourceMAC, destMAC) then how is this transmission smoothly resumed in a hypothetical successive SP between the two STAs, which has to have allocation ID different from 0? We should discuss, I'm not saying my solution is the best one. Probably the best solution is to completely re-write these parts of code

File: src/wifi/model/mac-low.cc (hunk 8 above)
Comment (tommyazz) [reply src/wifi/model/mac-low.cc:578]: Because we could remove the stored allocation if there's not enough time to complete the transmission of the resumed packet.

File: src/wifi/model/dca-txop.cc (hunk 3 above)
Comment (tommyazz) [reply src/wifi/model/dca-txop.cc:278]: Collisions with a future PR request on Hany's code? Or what?

File: src/wifi/model/mac-low.h [hunk 17]
```diff
@@ -390,23 +390,40 @@ class MacLow : public Object
...
    */
   void ResumeTransmission (Time duration, Ptr<DcaTxop> dca);
-
+  /**
+   * Change the Destination MAC address for a specific traffic flow.
+   * \param currentSrc The current source MAC address of the traffic flow.
+   * \param currentDst The current dest MAC address of the traffic flow.
+   * \param destAdd The new dest MAC address for the traffic flow.
+   *
+   * This function is used during relay operations in IEEE 802.11ad.
```
Comment (mattia-lecci) [inline src/wifi/model/mac-low.h:399]: i've never seen documentation appearing after the parameter definition :)

**Review by mattia-lecci — COMMENTED** [review]
i agree with @MatteoDrago about the code walkthrough

**Review by MatteoDrago — APPROVED** [review]
