### PR TITLE
Fixed issue with A-BFT start and issue with TXOP limits in 11ad

### LINKED ISSUE #1: TXOP Limit is not updated to 80211ad 2016 standard - Clause 20

### LINKED ISSUE #3: Starting time of A-BFT period is delayed at DMG STA with respect to PCP/AP
The A-BFT access period starts with a delay of some nanoseconds at the DMG STA with respect to the PCP/AP. This is due to the fact that the propagation delay is not taken into account when the start of the A-BFT is scheduled at the DMG STA.

### PR DESCRIPTION
**Pull request by tommyazz**
Fixed issue related to different starting times for the A-BFT period at DMG STA and PCP/AP. 
Set the TXOP limit for each AC as described in IEEE 802.11-2016

Fixed issues:

- Fix #1 
- Fix #3

### CODE REVIEW

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 1]
```diff
@@ -253,6 +253,8 @@ main (int argc, char *argv[])
   double simulationTime = 10;                   /* Simulation time in seconds. */
   bool pcapTracing = false;                     /* PCAP Tracing is enabled or not. */
   std::map<std::string, std::string> tcpVariants; /* List of the tcp Variants */
+  uint16_t tos = 0;                             /* Select AC_BE as default AC */
```
Comment (mattia-lecci) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: tos should be uint8_t looking at InetSocketAddress::SetTos

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 2]
```diff
@@ -253,6 +253,8 @@ main (int argc, char *argv[])
...
+  std::vector<uint8_t> tosValues = {0x70, 0x28, 0xb8, 0xc0}; /* AC_BE, AC_BK, AC_VI, AC_VO */
```
Comment (mattia-lecci) [inline scratch/evaluate_qd_channel_lroom_scenario.cc:283]: If possible, give reference to where these values can be found. makes debugging easier

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 3]
```diff
@@ -375,10 +378,17 @@ main (int argc, char *argv[])
...
+                   "BK_MaxAmsduSize", UintegerValue (msduAggregationSize),
+                   "VI_MaxAmpduSize", UintegerValue (mpduAggregationSize),
+                   "VI_MaxAmsduSize", UintegerValue (msduAggregationSize),
                    "SSSlotsPerABFT", UintegerValue (8), "SSFramesPerSlot", UintegerValue (13),
                    "BeaconInterval", TimeValue (MicroSeconds (102400)),
                    "ATIPresent", BooleanValue (false));
 
+  wifiMac.SetAttribute ("VO_MaxAmpduSize", UintegerValue (mpduAggregationSize),
+                        "VO_MaxAmsduSize", UintegerValue (msduAggregationSize));
+
```
Comment (mattia-lecci) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: I'd put all max packet size definitions either in SetType or SetAttrubute, but it's just for aesthetics

File: scratch/evaluate_qd_channel_lroom_scenario.cc (hunk 1 above)
Comment (tommyazz) [reply scratch/evaluate_qd_channel_lroom_scenario.cc]: It's just an index to tosValues vector. I changed the name of this variable in the last commit. It should be more clear now.

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 4]
```diff
@@ -175,16 +177,43 @@ MacRxOk (Ptr<DmgWifiMac> WifiMac, Ptr<OutputStreamWrapper> stream,
     }
 }
 
+void
+CwTrace (uint32_t oldCw, uint32_t newCw)
+{
+  // std::cout << "Old Cw: " << oldCw << ", New Cw: " << newCw << std::endl;
```
Comment (MatteoDrago) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: Instead of commenting the entire method (making it idealy useless), use `NS_LOG_DEBUG` in place of `std::cout`, so it can be activated directly from command line

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 5]
```diff
@@ -175,16 +177,43 @@ MacRxOk (Ptr<DmgWifiMac> WifiMac, Ptr<OutputStreamWrapper> stream,
...
+}
 
+void
+CongStateTrace (TcpSocketState::TcpCongState_t oldState, TcpSocketState::TcpCongState_t newState)
+{
+  // std::cout << "Old State: " << oldState << ", New State: " << newState << std::endl;
```
Comment (MatteoDrago) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: same as above

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 6]
```diff
@@ -295,6 +329,12 @@ main (int argc, char *argv[])
   Config::SetDefault ("ns3::WifiRemoteStationManager::RtsCtsThreshold", StringValue ("999999"));
   Config::SetDefault ("ns3::QueueBase::MaxPackets", UintegerValue (queueSize));
 
+  RngSeedManager::SetSeed (1);
+  RngSeedManager::SetRun (1);
+
+  //LogComponentEnable ("EdcaTxopN", LOG_LEVEL_ALL);
```
Comment (MatteoDrago) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: remove if not useful

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 7]
```diff
@@ -295,6 +329,12 @@ main (int argc, char *argv[])
...
+  //LogComponentEnable ("DcfManager", LOG_LEVEL_ALL);
```
Comment (MatteoDrago) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: same as above

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 8]
```diff
@@ -193,6 +222,7 @@ StationAssoicated (Ptr<DmgWifiMac> staWifiMac, Mac48Address address, uint16_t ai
     {
       bulk->StartApplication ();
     }
+  ConnectTcpTraces ();
```
Comment (MatteoDrago) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: you can check the socket type directly here upon calling the method, so you do it just once :)

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 9]
```diff
@@ -470,7 +525,7 @@ main (int argc, char *argv[])
 
   /** Connect Traces **/
   AsciiTraceHelper ascii;
-  Ptr<OutputStreamWrapper> outputSlsPhase = ascii.CreateFileStream ("slsResults" + arrayConfig + ".csv");
+  Ptr<OutputStreamWrapper> outputSlsPhase = ascii.CreateFileStream ("../output/slsResults" + arrayConfig + ".csv");
```
Comment (MatteoDrago) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: the folder where the code put its output files is related to users preferences.. I'd avoid specifying folders on public code, I'd do it just on my local repo :) It could create less issues also on possible merges with the official repo

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 10]
```diff
@@ -489,13 +544,13 @@ main (int argc, char *argv[])
...
   parametersSta->wifiMac = staWifiMac;
-  staWifiMac->TraceConnectWithoutContext ("Assoc", MakeBoundCallback (&StationAssoicated, staWifiMac));
+  staWifiMac->TraceConnectWithoutContext ("Assoc", MakeBoundCallback (&StationAssociated, staWifiMac));
   staWifiMac->TraceConnectWithoutContext ("SLSCompleted", MakeBoundCallback (&SLSCompleted, outputSlsPhase, parametersSta));
   staWifiPhy->TraceConnectWithoutContext ("PhyTxEnd", MakeCallback (&PhyTxEnd));
   staRemoteStationManager->TraceConnectWithoutContext ("MacTxDataFailed", MakeCallback (&MacTxDataFailed));
 
   /* Get SNR Traces */
-  Ptr<OutputStreamWrapper> snrStream = ascii.CreateFileStream ("snrValues.csv");
+  Ptr<OutputStreamWrapper> snrStream = ascii.CreateFileStream ("../output/snrValues.csv");
```
Comment (MatteoDrago) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: same as above

File: src/wifi/model/dmg-ap-wifi-mac.cc [hunk 11]
```diff
@@ -945,6 +945,7 @@ DmgApWifiMac::FrameTxOk (const WifiMacHeader &hdr)
         {
           NS_LOG_DEBUG ("DMG PCP/AP completed the transmission of the last DMG Beacon at " << Simulator::Now ());
           Time startTime = m_nextDmgBeaconDelay + GetMbifs ();
+          NS_ASSERT (Simulator::Now () + startTime == Simulator::Now () + GetBTIRemainingTime () + GetMbifs ());
```
Comment (MatteoDrago) [inline src/wifi/model/dmg-ap-wifi-mac.cc]: comment this, or use `NS_ASSERT_MSG` (probably better)

File: src/wifi/model/dmg-sta-wifi-mac.cc [hunk 12]
```diff
@@ -3076,7 +3076,7 @@ DmgStaWifiMac::Receive (Ptr<Packet> packet, const WifiMacHeader *hdr)
 
               /* Organizing medium access periods (Synchronization with TSF) */
               m_abftDuration = m_ssSlotsPerABFT * GetSectorSweepSlotTime (m_ssFramesPerSlot);
-//              m_biStartTime = MicroSeconds (beacon.GetTimestamp ()) + hdr->GetDuration () - m_btiDuration;
+//            m_biStartTime = MicroSeconds (beacon.GetTimestamp ()) + hdr->GetDuration () - m_btiDuration;
```
Comment (MatteoDrago) [inline src/wifi/model/dmg-sta-wifi-mac.cc:3079]: remove if not useful

File: src/wifi/model/dmg-sta-wifi-mac.cc [hunk 13]
```diff
@@ -3098,8 +3098,10 @@ DmgStaWifiMac::Receive (Ptr<Packet> packet, const WifiMacHeader *hdr)
               if (!beaconInterval.IsDiscoveryMode ())
                 {
                   /* This function is triggered on NanoSeconds basis and Thr duration field is in MicroSeconds basis */
-                  Time dmgBeaconDurationUs = MicroSeconds (ceil (static_cast<double> (m_phy->GetLastRxDuration ().GetNanoSeconds ()) / 1000));
-                  Time startTime = hdr->GetDuration () + (dmgBeaconDurationUs - m_phy->GetLastRxDuration ()) + GetMbifs ();
+                  //Time dmgBeaconDurationUs = MicroSeconds (ceil (static_cast<double> (m_phy->GetLastRxDuration ().GetNanoSeconds ()) / 1000));
```
Comment (MatteoDrago) [inline src/wifi/model/dmg-sta-wifi-mac.cc:3101]: remove if not useful

File: src/wifi/model/dmg-sta-wifi-mac.cc [hunk 14]
```diff
@@ -3098,8 +3098,10 @@ DmgStaWifiMac::Receive (Ptr<Packet> packet, const WifiMacHeader *hdr)
...
+                  //Time startTime = hdr->GetDuration () + (dmgBeaconDurationUs - m_phy->GetLastRxDuration ()) + GetMbifs ();
```
Comment (MatteoDrago) [inline src/wifi/model/dmg-sta-wifi-mac.cc:3102]: remove if not useful

File: src/wifi/model/wifi-mac.h [hunk 15]
```diff
@@ -325,7 +325,7 @@ class WifiMac : public Object
    *
    * Configure the DCF with appropriate values depending on the given access category.
    */
-  void ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac);
+  void ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac, bool isDmg = false);
```
Comment (MatteoDrago) [inline src/wifi/model/wifi-mac.h]: Add isDmG parameter description in the method doxy

Comment (MatteoDrago) [reply src/wifi/model/wifi-mac.h]: Also, I'd modify the parameter name to isDmgSupported

**Review by MatteoDrago — CHANGES_REQUESTED** [review]
Is it normal that the waf-tools folder is in our master branch? I assume it has been forked as it is from Hany, so I wonder if we have to leave it there.

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 16]
```diff
@@ -550,10 +555,10 @@ main (int argc, char *argv[])
               std::cout << "Flow " << i->first << " (" << t.sourceAddress << " -> " << t.destinationAddress << ")" << std::endl;
               std::cout << "  Tx Packets: " << i->second.txPackets << std::endl;
               std::cout << "  Tx Bytes:   " << i->second.txBytes << std::endl;
-              std::cout << "  TxOffered:  " << i->second.txBytes * 8.0 / ((simulationTime - 1) * 1e6)  << " Mbps" << std::endl;
+              std::cout << "  TxOffered:  " << i->second.txBytes * 8.0 / ((simulationTime - appStartTime.GetSeconds ()) * 1e6)  << " Mbps" << std::endl;
```
Comment (mattia-lecci) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: repeated non-trivial command: save it as a variable to make it a single point of failure

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 17]
```diff
@@ -550,10 +555,10 @@ main (int argc, char *argv[])
...
               std::cout << "  Rx Packets: " << i->second.rxPackets << std::endl;
               std::cout << "  Rx Bytes:   " << i->second.rxBytes << std::endl;
-              std::cout << "  Throughput: " << i->second.rxBytes * 8.0 / ((simulationTime - 1) * 1e6)  << " Mbps" << std::endl;
+              std::cout << "  Throughput: " << i->second.rxBytes * 8.0 / ((simulationTime - appStartTime.GetSeconds ()) * 1e6)  << " Mbps" << std::endl;
```
Comment (mattia-lecci) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: same as above

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 18]
```diff
@@ -572,7 +577,7 @@ main (int argc, char *argv[])
 
       std::cout << "  Rx Packets: " << packetSink->GetTotalReceivedPackets () << std::endl;
       std::cout << "  Rx Bytes:   " << packetSink->GetTotalRx () << std::endl;
-      std::cout << "  Throughput: " << packetSink->GetTotalRx () * 8.0 / ((simulationTime - 1) * 1e6) << " Mbps" << std::endl;
+      std::cout << "  Throughput: " << packetSink->GetTotalRx () * 8.0 / ((simulationTime - appStartTime.GetSeconds ()) * 1e6) << " Mbps" << std::endl;
```
Comment (mattia-lecci) [inline scratch/evaluate_qd_channel_lroom_scenario.cc:603]: same as above

File: src/wifi/model/dmg-sta-wifi-mac.cc [hunk 19]
```diff
@@ -3098,8 +3098,10 @@ DmgStaWifiMac::Receive (Ptr<Packet> packet, const WifiMacHeader *hdr)
...
+                  Time btiDuration = MicroSeconds (operationElement->GetMinBHIDuration ()) - m_abftDuration - m_atiDuration - 2 * GetMbifs ();
+                  Time startTime = btiDuration - (Simulator::Now () - m_biStartTime) + GetMbifs ();
```
Comment (mattia-lecci) [inline src/wifi/model/dmg-sta-wifi-mac.cc:3104]: Using m_biStartTime is a bit like cheating: you are assuming perfect synchronization between the AP and the STA clocks

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 20]
```diff
@@ -300,6 +328,9 @@ main (int argc, char *argv[])
   Config::SetDefault ("ns3::WifiRemoteStationManager::RtsCtsThreshold", StringValue ("999999"));
   Config::SetDefault ("ns3::QueueBase::MaxPackets", UintegerValue (queueSize));
 
+  RngSeedManager::SetSeed (1);
+  RngSeedManager::SetRun (1);
```
Comment (mattia-lecci) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: run number could be set from terminal

File: src/wifi/model/dmg-sta-wifi-mac.cc (hunk 12 above)
Comment (tommyazz) [reply src/wifi/model/dmg-sta-wifi-mac.cc:3079]: Old code. Might be useful in the future

File: src/wifi/model/wifi-mac.cc [hunk 21]
```diff
@@ -478,7 +478,7 @@ WifiMac::Configure80211ad (void)
 }
 
 void
-WifiMac::ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac)
+WifiMac::ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac, bool isDmg)
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.cc]: I would pass a WifiPhyStandard instead of isDmg, see next comment(s)

File: src/wifi/model/wifi-mac.cc [hunk 22]
```diff
@@ -494,7 +494,15 @@ WifiMac::ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool is
...
-          dcf->SetTxopLimit (MicroSeconds (1504));
+          if (isDmg)
+            {
+              /* See IEEE802.11-2016 Table 9-137 (Clause 20) */
+              dcf->SetTxopLimit (MicroSeconds (0));
+            }
+          else 
+            {
+              dcf->SetTxopLimit (MicroSeconds (1504));
+            }
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.cc]: Given the 2016 specs, I would rather do a nested switch/case:
- one on the AC traffic
- one on the type of standard (clause) used
And thus implement all TXOPs for the different clauses

File: src/wifi/model/wifi-mac.cc [hunk 23]
```diff
@@ -507,7 +515,15 @@ WifiMac::ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool is
...
-          dcf->SetTxopLimit (MicroSeconds (3008));
+          if (isDmg)
+            {
+              /* See IEEE802.11-2016 Table 9-137 (Clause 20) */
+              dcf->SetTxopLimit (MicroSeconds (0));
+            }
+          else
+            {
+              dcf->SetTxopLimit (MicroSeconds (3008));
+            }
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.cc]: same as above

File: src/wifi/model/wifi-mac.cc (hunk 21 above)
Comment (mattia-lecci) [reply src/wifi/model/wifi-mac.cc]: PS: not sure if it is easy to get it. we can talk about it offline

File: src/wifi/model/wifi-mac.h (hunk 15 above)
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.h]: same as above

File: scratch/evaluate_qd_channel_lroom_scenario.cc (hunk 16 above)
Comment (tommyazz) [reply scratch/evaluate_qd_channel_lroom_scenario.cc]: What's the repeated command? The simulation duration computation?

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 24]
```diff
@@ -285,11 +315,17 @@ main (int argc, char *argv[])
   cmd.AddValue ("enableMobility", "Whether to enable mobility or simulate static scenario", enableMobility);
   cmd.AddValue ("verbose", "Turn on all WifiNetDevice log components", verbose);
   cmd.AddValue ("simulationTime", "Simulation time in seconds", simulationTime);
+  cmd.AddValue ("ac", "0: AC_BE, 1: AC_BK, 2: AC_VI, 3: AC_VO", ac);
   cmd.AddValue ("pcap", "Enable PCAP Tracing", pcapTracing);
   cmd.AddValue ("arrayConfig", "Antenna array configuration", arrayConfig);
+  cmd.AddValue ("seed", "Seed number for this simulation", seed);
+  cmd.AddValue ("run", "Run number for this simulation", run);
```
Comment (MatteoDrago) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: Not needed.. Run and Seed numbers are already available in the command line, specifically with --RngRun and --RngSeed :)

File: scratch/evaluate_qd_channel_lroom_scenario.cc [hunk 25]
```diff
@@ -285,11 +315,17 @@ main (int argc, char *argv[])
...
   cmd.AddValue ("csv", "Enable CSV output instead of plain text. This mode will suppress all the messages related statistics and events.", csv);
   cmd.Parse (argc, argv);
 
+  RngSeedManager::SetSeed (seed);
+  RngSeedManager::SetRun (run);
```
Comment (MatteoDrago) [inline scratch/evaluate_qd_channel_lroom_scenario.cc]: To be modified accordingly to the comment above

**Review by MatteoDrago — CHANGES_REQUESTED** [review]

File: scratch/evaluate_qd_channel_lroom_scenario.cc (hunk 24 above)
Comment (tommyazz) [reply scratch/evaluate_qd_channel_lroom_scenario.cc]: it's the same in the end

Comment (MatteoDrago) [reply scratch/evaluate_qd_channel_lroom_scenario.cc]: I know, but if there's already something that does that for you, there's no need to add it

Comment (tommyazz) [reply scratch/evaluate_qd_channel_lroom_scenario.cc]: I'd prefer the first syntax since then the line of code that launches the simulation is cleaner

**Review by MatteoDrago — APPROVED** [review]

File: src/wifi/model/wifi-mac.cc [hunk 26]
```diff
@@ -478,49 +478,151 @@ WifiMac::Configure80211ad (void)
 }
 
 void
-WifiMac::ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac)
+WifiMac::ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac, bool isDmgSupported)
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.cc]: isDmgSupported is not needed anymore
Same goes for isDsss

File: src/wifi/model/wifi-mac.cc [hunk 27]
```diff
@@ -478,49 +478,151 @@ WifiMac::Configure80211ad (void)
...
+            {
+              dcf->SetTxopLimit (MicroSeconds (3264));
+            }
+          else
+            {
+              dcf->SetTxopLimit (MicroSeconds (2080));
+            }
+          break;
+        default:
+          NS_FATAL_ERROR ("Unsupported WifiPhyStandard in WifiMac::ConfigureDcf ()");
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.cc]: to make it easier to compare it to the standard, please add comments explaining which clauses they refer to

File: src/wifi/model/wifi-mac.cc [hunk 28]
```diff
@@ -478,49 +478,151 @@ WifiMac::Configure80211ad (void)
...
+        case WIFI_PHY_STANDARD_80211_5MHZ:
+        case WIFI_PHY_STANDARD_80211b:
+          if (isDsss)
+            {
+              dcf->SetTxopLimit (MicroSeconds (3264));
+            }
+          else
+            {
+              dcf->SetTxopLimit (MicroSeconds (2080));
+            }
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.cc]: This should not be needed anymore

File: src/wifi/model/wifi-mac.cc [hunk 29]
```diff
@@ -478,49 +478,151 @@ WifiMac::Configure80211ad (void)
...
+        case WIFI_PHY_STANDARD_80211b:
+          if (isDsss)
+            {
+              dcf->SetTxopLimit (MicroSeconds (6016));
+            }
+          else
+            {
+              dcf->SetTxopLimit (MicroSeconds (4096));
+            }
+          break;
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.cc]: see comments above

File: src/wifi/model/wifi-mac.cc [hunk 30]
```diff
@@ -478,49 +478,151 @@ WifiMac::Configure80211ad (void)
...
+        case WIFI_PHY_STANDARD_80211_5MHZ:
+        case WIFI_PHY_STANDARD_80211b:
+          if (isDsss)
+            {
+              dcf->SetTxopLimit (MicroSeconds (3264));
+            }
+          else
+            {
+              dcf->SetTxopLimit (MicroSeconds (2528));
+            }
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.cc]: see comments above

File: src/wifi/model/wifi-mac.cc [hunk 31]
```diff
@@ -478,49 +478,151 @@ WifiMac::Configure80211ad (void)
...
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.cc]: see comments above

File: src/wifi/model/wifi-mac.h [hunk 32]
```diff
@@ -322,10 +322,11 @@ class WifiMac : public Object
    * \param cwmax the maximum congestion window for the DCF
    * \param isDsss flag to indicate whether PHY is DSSS or HR/DSSS
    * \param ac the access category for the DCF
+   * \param isDmgSupported flag to indicate whether PHY is DMG
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.h]: see comments above

File: src/wifi/model/wifi-mac.h [hunk 33]
```diff
@@ -322,10 +322,11 @@ class WifiMac : public Object
    * \param cwmax the maximum congestion window for the DCF
    * \param isDsss flag to indicate whether PHY is DSSS or HR/DSSS
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.h]: see comments above

File: src/wifi/model/wifi-mac.h [hunk 34]
```diff
@@ -322,10 +322,11 @@ class WifiMac : public Object
...
    * \param ac the access category for the DCF
+   * \param isDmgSupported flag to indicate whether PHY is DMG
    *
    * Configure the DCF with appropriate values depending on the given access category.
    */
-  void ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac);
+  void ConfigureDcf (Ptr<DcaTxop> dcf, uint32_t cwmin, uint32_t cwmax, bool isDsss, AcIndex ac, bool isDmgSupported = false);
```
Comment (mattia-lecci) [inline src/wifi/model/wifi-mac.h]: see comments above

**Review by mattia-lecci — APPROVED** [review]

**Review by MatteoDrago — APPROVED** [review]
